image: swift:5.0

before_script:
  # use the Gitlab CI Job token to login for all git clones on the machine.
  - echo -e "machine gitlab.com\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc

stages: 
  - test
  - build_release
  
build_project:
  stage: build_release
  script:
    - swift package reset
    - swift build -c release
  tags:
    - docker
  only:
    - master

test_project:
  stage: test
  variables:
    GIT_DEPTH: "50"
  script:
    - swift package reset
    - swift test
  tags:
    - docker